all if-up tasks are now sent into the background and told to wait until tty becomes available also, fixed indention in tcpprint

diff --git a/config/includes.chroot/lib/live/config/2000-settime b/config/includes.chroot/lib/live/config/2000-settime
--- a/config/includes.chroot/lib/live/config/2000-settime
+++ b/config/includes.chroot/lib/live/config/2000-settime
@@ -15,15 +15,21 @@ if [ "$METHOD" = loopback ]; then
         exit 0
 fi
 
-while [ -z "\$(hostname -I)" ] ; do
-	echo -en "\n'\$0' is waiting for a client IP." | tee -a /dev/tty8
-	sleep 2
-done
-if ntpdate-debian -s && hwclock --systohc ; then
-	echo -en "\n\$(date +'%F | %T | ')'\$0' - time has been set." | tee -a /dev/tty8
-else
-	echo -en "\n\$(date +'%F | %T | ')'\$0' - error setting time. Timestamps will be based on CMOS Clock." | tee -a /dev/tty8
-fi
+(
+	while ! [ -c /dev/tty8 ] ; do
+		echo -en "\n'\$0' is waiting for tty8 to become available."
+		sleep 2
+	done
+	while [ -z "\$(hostname -I)" ] ; do
+		echo -en "\n'\$0' is waiting for a client IP." | tee -a /dev/tty8
+		sleep 2
+	done
+	if ntpdate-debian -s && hwclock --systohc ; then
+		echo -en "\n\$(date +'%F | %T | ')'\$0' - time has been set." | tee -a /dev/tty8
+	else
+		echo -en "\n\$(date +'%F | %T | ')'\$0' - error setting time. Timestamps will be based on CMOS Clock." | tee -a /dev/tty8
+	fi
+) &
 SETTIME
 
 chmod 755 /etc/network/if-up.d/0050-settime
