logging was still broken

diff --git a/config/includes.chroot/lib/live/config/2600-tcpprint b/config/includes.chroot/lib/live/config/2600-tcpprint
--- a/config/includes.chroot/lib/live/config/2600-tcpprint
+++ b/config/includes.chroot/lib/live/config/2600-tcpprint
@@ -8,6 +8,12 @@ TcpPrint ()
 echo -n " tcpprint"
 
 if grep -q "\W*tcpprint\W*" /proc/cmdline ; then
+
+	while ! [ -s /var/run/availablevt ] ; do
+		echo -en "\n'\$0' is waiting for a free console."
+		sleep 2
+	done
+
         TCPPRINTONLYFROM=$(cat /proc/cmdline | \
                        tr ' ' '\n' | \
                        awk -F'=' ' /^tcpprintonlyfrom=/ { print $2 }')
@@ -28,7 +34,7 @@ if grep -q "\W*tcpprint\W*" /proc/cmdline ; then
 	[ -d /dev/usb ] && PRINTERDEVICES=$(find /dev/usb -type c -name "lp*" | sort)
 	PRINTERDEVICES="$PRINTERDEVICES $(find /dev/ -maxdepth 1 -type c -name "lp*" | sort)"
 
-	echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty\$(fgconsole -n)
+	echo -en "\n\$(date +'%F | %T | ')'\$0' is waiting for a client IP." | tee -a /dev/tty\$(cat /var/run/availablevt)
 
 	# Create a listening port for a TCP/9100-RAW-printer
 	#
@@ -52,21 +58,21 @@ service jetdirect${PRINTERCOUNT}
 	$TCPPRINTONLYFROM
 }
 JETDIRCONF
-		echo -en "\n\$(date +'%F | %T | ')Mapping $PRINTERDEV => $PORTNUMBER" | tee -a /dev/tty\$(fgconsole -n)
+		echo -en "\n\$(date +'%F | %T | ')Mapping $PRINTERDEV => $PORTNUMBER" | tee -a /dev/tty\$(cat /var/run/availablevt)
 		PRINTERCOUNT=$((PRINTERCOUNT+1))
 	done
 
 	echo "#Local printer config: Done." >/etc/xinetd.d/jetdirect
 
 	if ps -C xinetd --no-header >/dev/null ; then
-		echo -en "\n\$(date +'%F | %T | ')xinetd needs to be restarted, trying to do that ..." | tee -a /dev/tty\$(fgconsole -n)
+		echo -en "\n\$(date +'%F | %T | ')xinetd needs to be restarted, trying to do that ..." | tee -a /dev/tty\$(cat /var/run/availablevt)
 		if /etc/init.d/xinetd restart; then
-			echo -n " success. All done." | tee -a /dev/tty\$(fgconsole -n)
+			echo -n " success. All done." | tee -a /dev/tty\$(cat /var/run/availablevt)
 		else
-			echo -n " error." | tee -a /dev/tty\$(fgconsole -n)
+			echo -n " error." | tee -a /dev/tty\$(cat /var/run/availablevt)
 		fi
 	else
-		echo -en "\n\$(date +'%F | %T | ')No xinetd restart necessary. All done." | tee -a /dev/tty\$(fgconsole -n)
+		echo -en "\n\$(date +'%F | %T | ')No xinetd restart necessary. All done." | tee -a /dev/tty\$(cat /var/run/availablevt)
 	fi
 
 	) &
